# Generated by Django 4.2 on 2023-04-26 18:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_email_verified_alter_user_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.SmallIntegerField(editable=False)),
                (
                    "expire_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            4,
                            26,
                            18,
                            13,
                            19,
                            497363,
                            tzinfo=datetime.timezone.utc,
                        ),
                        editable=False,
                    ),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
