# Generated by Django 4.2 on 2023-04-27 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expire_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 27, 17, 50, 15, 718829, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.SmallIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
