# Generated by Django 4.2 on 2023-05-03 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_otp_expire_at_alter_otp_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expire_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 3, 14, 51, 35, 47975, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.CreateModel(
            name="NotificationDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, editable=False)),
                (
                    "notification_token",
                    models.CharField(editable=False, max_length=350),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
