# Generated by Django 4.2 on 2023-04-09 13:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import post_real.core.image_size_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("caption", models.CharField(max_length=100)),
                (
                    "description",
                    models.TimeField(blank=True, max_length=500, null=True),
                ),
                (
                    "postPicUrl",
                    models.ImageField(
                        upload_to="mediafiles/postPics/",
                        validators=[
                            post_real.core.image_size_validator.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpeg", "jpg", "png"]
                            ),
                        ],
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
