# Generated by Django 4.2 on 2023-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
