# Generated by Django 4.2 on 2023-04-11 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commented_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="postId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_post",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="liked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="postId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_post",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
