# Generated by Django 4.2 on 2023-04-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_commented_by_alter_comment_postid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="like",
            name="is_active",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
