"""
Django settings for post_real project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from .base import *
from .apps import *
from .auth import *
from .database import *
from .drf import *
from .middleware import *
from .template import *
from .cors import *